N_Asset/N_Asset/urls.py
"""
Definition of urls for N_Asset.
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from app.NA_Views.MasterData import NA_Privilege_View
from app.NA_Views import NA_User_View
import app.views
# Uncomment the next lines to enable the admin:
# admin.autodiscover()
from django.contrib import admin
from social_django.urls import *
urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),

    # User's URL
    url(r'^login/$', NA_Privilege_View.na_privilege_login, name='login'),
    url(r'^register/$', NA_Privilege_View.na_privilege_register,
        name='NA_User_Register'),
    url(r'^profile/(?P<username>\w+)/edit/$',
        NA_User_View.user_profile, name='user_profile'),
    url(r'^logout/$', NA_Privilege_View.NA_Privilege_logout, name='logout'),

    # Master Data URL
    url(r'^MasterData/', include('app.NA_Urls.MasterData_url', namespace='MasterData')),

    # Transactions URL
    url(r'^Transactions/',
        include('app.NA_Urls.Transactions_url', namespace='Transactions')),

    # Other Pages URL
    url(r'^OtherPages/', include('app.NA_Urls.OtherPages_url', namespace='OtherPages')),
    
    url(r'^Report/', include('app.NA_Urls.Reports_url', namespace='Report')),

    # Notifications URL
    url(r'^Notifications/', include('NA_Notifications.urls',
                                    namespace='NA_Notifications')),

    # URL Facebook,Google,Twitter Login
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
]

# untuk akses url media(picture) hasil upload User
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    #import debug_toolbar
    #urlpatterns += [
    #   url(r'^__debug__/', include(debug_toolbar.urls)),]

N_Asset/NA_Notifications/models.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.utils.functional import cached_property

from NA_DataLayer.fields import JSONField


User = get_user_model()


class NANotifications(models.Model):

    idapp = models.AutoField(primary_key=True, db_column='idapp')
    user = models.ManyToManyField(
        User,
        db_constraint=False
    )
    name = models.CharField(max_length=100, db_column='name')
    title = models.CharField(max_length=150, db_column='title')
    message = models.CharField(max_length=255, db_column='message')
    is_active = models.BooleanField(default=True, db_column='is_active')
    data = JSONField(db_column='data')
    created_date = models.DateTimeField(db_column='created_date')

    def __str__(self):
        return self.name

    @cached_property
    def recipients(self):
        return list(self.user.all())

    @classmethod
    @transaction.atomic
    def push_notifications(cls, to, name, title, message, data):
        notifications = cls()
        notifications.name = name
        notifications.title = title
        notifications.message = message
        notifications.data = data
        notifications.created_date = datetime.now()
        notifications.save()

        if isinstance(to, models.query.QuerySet):
            to = list(to)
        notifications.user.add(*to)

    @classmethod
    def dismiss_notifications(cls, notif_id):
        filter_kwargs = {
            'idapp': notif_id
        }
        if isinstance(notif_id, list):
            filter_kwargs = {
                'idapp__in': notif_id
            }
        notifications = cls.objects.filter(**filter_kwargs)
        for notif in notifications:
            notif.data.update({
                'is_dismissed': True
            })
            notif.save()

    class Meta:
        managed = True
        db_table = 'n_a_notifications'

N_Asset/app/templates/app/MasterData/NA_Entry.html
<!--
    idapp = models.IntegerField(db_column='IDApp',primary_key=True)  # Field name made lowercase.
    itemcode = models.CharField(db_column='ItemCode', max_length=30)  # Field name made lowercase.
    goodsname = models.CharField(db_column='GoodsName', max_length=100)  # Field name made lowercase.
    brandname = models.CharField(db_column='BrandName', max_length=50, blank=True, null=True)  # Field name made lowercase.
    typeapp = models.CharField(db_column='TypeApp', max_length=32)  # Field name made lowercase.
    priceperunit = models.DecimalField(db_column='PricePerUnit', max_digits=10,decimal_places=4)  # Field name made lowercase.
    depreciationmethod = models.CharField(db_column='DepreciationMethod', max_length=2)  # Field name made lowercase.
    unit = models.CharField(db_column='Unit', max_length=30)  # Field name madelowercase.
    economiclife = models.DecimalField(db_column='EconomicLife', max_digits=10,decimal_places=2)  # Field name made lowercase.
    placement = models.CharField(db_column='Placement', max_length=50, blank=True, null=True)  # Field name made lowercase.
    descriptions = models.CharField(db_column='Descriptions', max_length=150, blank=True, null=True)  # Field name made lowercase.
    inactive = models.IntegerField(db_column='InActive', blank=True, null=True) # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate')  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=100, blank=True, null=True)  # Field name made lowercase.
    modifieddate = models.DateTimeField(db_column='ModifiedDate', blank=True, null=True)  # Field name made lowercase.
    modifiedby = models.CharField(db_column='ModifiedBy', max_length=100, blank=True, null=True)
-->
<div class="row" style="overflow:auto;">
    <!--
//================load jquery-ui.min.js untuk ngaktifkan autocomplete ================

    -->
    
    <!--Bagi dua Rownya-->
    <div class="col-md-12">
        <form action="." method="post" class="form-horizontal" enctype="multipart/form-data" style="background-color:transparent;font-size: 1em;" id="frm-NA-Entry-Goods" onsubmit="return false;">
            {% csrf_token %}

            <div class="NA-Entry-div-row">
                <div class="NA-Entry-inlinve-div">
                    <label for="itemcode" class="NA-Entry-label;">Item Code</label>
                    {{ form.itemcode }}
                </div>
                <div class="NA-Entry-inlinve-div"  style="padding-left:3px;">
                    <label for="goodsname" class="NA-Entry-label;">goods name</label>
                    {{ form.goodsname }}
                </div>
                <div class="NA-Entry-inlinve-div">
                    <label for="brandname" class="NA-Entry-label;">Brand Name</label>
                    {{ form.brandname }}
                </div>
            </div>
            <div class="NA-Entry-div-row">
                <div class="NA-Entry-inlinve-div">
					<fieldset>
						<legend>Category</legend>
							{{ form.typeapp }}
					</fieldset>                   
                </div>
                <div class="NA-Entry-inlinve-div" style="padding-left:5px;">
                    <label for="priceperunit" class="NA-Entry-label;">Price/Unit</label>
                    {{ form.priceperunit }}
                </div>
                <div class="NA-Entry-inlinve-div" style="vertical-align:bottom">
                    <fieldset>
                        <legend>Unit</legend>
                        {{ form.unit }}
                    </fieldset>
                </div>
                <div class="NA-Entry-inlinve-div" style="vertical-align:bottom">
                    <fieldset>
                        <legend>placement</legend>
                        {{ form.placement }}
                    </fieldset>
                </div>
            </div>
            <div class="NA-Entry-div-row">
                <div class="NA-Entry-inlinve-div" style="vertical-align: bottom;">
                    <fieldset>
                        <legend>economiclife</legend>
                        {{ form.economiclife }}
                    </fieldset>
                </div>
                <div class="NA-Entry-inlinve-div">
                    <fieldset style="margin-left:auto;">
                        <legend>Depreciation Method</legend>
                        {{ form.depreciationmethod }}
                    </fieldset>
                </div>
                <div class="NA-Entry-inlinve-div">
				 <label>  {{ form.inactive }} In Active </label>
                   
                </div>
            </div>
            <div class="NA-Entry-div-row">
                 <div class="NA-Entry-inlinve-div">
                    <label for="descriptions" class="NA-Entry-label;">Descriptions / Remark/Unit</label>
                    {{ form.descriptions }}
                </div>                
            </div>
             <input type="submit" style="display:none" id="inputButton">  
            {{ form.status }}
            {{ form.initializeForm }}
            {{ form.idapp}}
          
        </form>
    </div>

</div>

N_Asset/app/templates/app/MasterData/NA_Entry_AccFA.html
<form action="ShowEntry/" method="post" style="width:480px;height:{{form.height}};padding-top:10px" id="acc_form" onsubmit="return false">
        {% csrf_token %}
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_itemcode" class="NA-Entry-label;">{{form.itemcode.label}}</label>
            {{ form.itemcode }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_typeApp">Type</label>
            {{ form.typeApp }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_goods_name" class="NA-Entry-label;">Goods</label>
            <div class="input-group" style="display:inline-flex;">
                {{ form.goods_name }}
                <div class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;">
                    <button class="btn btn-success" type="button" id="fk_goodsname"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </div>
    </div>
    {% if mode == 'Add' %}
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label>{{form.economiclife.label}}</label>
            {{ form.economiclife }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_price" class="NA-Entry-label;">Price</label>
            {{ form.price }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_serialNumber" class="NA-Entry-label;">Serial Number</label>
            {{ form.serialNumber }}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_startdate" class="NA-Entry-label;">Start Date</label>
            {{ form.startdate }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_enddate" class="NA-Entry-label;">End Date</label>
            {{ form.enddate }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_depr_method">Depreciation Method</label>
            {{form.depr_method}}
        </div>
    </div>
    {% elif mode == 'Open' %}
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="{{form.year.id}}" class="NA-Entry-label;">{{form.year.label}}</label>
            {{ form.year }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label>{{form.economiclife.label}}</label>
            {{ form.economiclife }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_serialNumber" class="NA-Entry-label;">Serial Number</label>
            {{ form.serialNumber }}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_price" class="NA-Entry-label;">Price</label>
            {{ form.price }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_depr_method">Depreciation Method</label>
            {{form.depr_method}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_startdate" class="NA-Entry-label;">Start Date</label>
            {{ form.startdate }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_enddate" class="NA-Entry-label;">End Date</label>
            {{ form.enddate }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_depr_expense">Depreciation Expense</label>
            {{form.depr_expense}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_depr_accumulation" class="NA-Entry-label;">{{form.depr_accumulation.label}}</label>
            {{ form.depr_accumulation }}
        </div>
        <div class="NA-Entry-inlinve-div">
            <div class="NA-Entry-inlinve-div">
                <label for="id_book_value">{{form.bookvalue.label}}</label>
                {{ form.bookvalue }}
            </div>
        </div>
    </div>
    {% endif %}
    {{form.fk_goods}}
    {{form.initializeForm}}
    <input type="submit" style="display:none" id="acc_submit" />
</form>

N_Asset/app/templates/app/MasterData/NA_Entry_GoodsLost.html
<style>
    .cust-horizontal {
        display: inline-block;
    }
</style>
<div class="row" style="overflow:auto;">
    <form action="ShowEntry/" method="post" style="width: 600px;max-width:700px;max-height:500px;" id="gLost_form"
        onsubmit="return false">
        {% csrf_token %}
        <fieldset style="margin-bottom:5px;">
            <legend>Goods that is lost info</legend>
            <div class="NA-Entry-div-row" style="display:flex;">
                <div class="NA-Entry-inlinve-div" style="width: 40%">
                    {{ form.serialNumber }}
                </div>
                <div class="NA-Entry-inlinve-div" style="width: 59%">
                    <div class="input-group" style="display:inline-flex;width:100%">
                        {{ form.goods }}
                        <div class="input-group-btn"
                            style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end;">
                            <button class="btn btn-success" type="button" id="fk_goods"><i
                                    class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="NA-Entry-div-row" style="display:flex;flex-flow:row nowrap">
                <div class="NA-Entry-inlinve-div" style="flex:0 1 auto;margin-right:4px">
                    <label for="id_typeApp" class="cust-horizontal" style="margin-right: 30px;">Type/<br />Item
                        Code</label>
                    {{ form.typeApp }}
                </div>
                <div class="NA-Entry-inlinve-div" style="align-self: flex-end">
                    {{ form.itemcode }}
                </div>
            </div>
            <div class="NA-Entry-div-row">
                <div class="NA-Entry-inlinve-div">
                    <label class="cust-horizontal" style="margin-right: 42px;">Used By</label>
                    {{ form.nik_used }}
                </div>
                <div class="NA-Entry-inlinve-div">
                    {{ form.empl_used }}
                </div>
            </div>
            <div class="NA-Entry-div-row">
                <div class="NA-Entry-inlinve-div">
                    <label for="id_startdate" class="cust-horizontal" style="margin-right: 17px;">Responsible<br />Person</label>
                    {{ form.nik_resp }}
                </div>
                <div class="NA-Entry-inlinve-div"  style="width: 59%">                
                    <div class="input-group" style="display:inline-flex;width:100%">
                        {{ form.empl_resp }}
                        <div class="input-group-btn"
                            style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end;">
                            <button class="btn btn-success" type="button" id="btnfindResp"><i
                                    class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="NA-Entry-div-row" style="display: flex">
            <div class="NA-Entry-inlinve-div" style="display: inline-flex;width:40%">
                <label for="id_nik_lostby" class="cust-horizontal" style="margin-right: 58px;">Lost by</label>
                {{ form.nik_lostby }}
            </div>
            <div class="NA-Entry-inlinve-div" style="display: inline-flex;width:59%;">
                <div class="input-group" style="display:inline-flex;width:100%">
                    {{ form.empl_lostby }}
                    <div class="input-group-btn"
                        style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end;">
                        <button class="btn btn-success" type="button" id="fk_lostby"><i
                                class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="NA-Entry-div-row">
            <div class="NA-Entry-inlinve-div">
                <label for="id_datelost" class="cust-horizontal" style="margin-right: 40px;">Date Lost</label>
                {{ form.datelost }}
            </div>
            <div class="NA-Entry-inlinve-div">
                <label for="id_status" class="cust-horizontal"></label>Status</label>
                {{ form.status_goods }}
            </div>
        </div>
        <div class="NA-Entry-div-row" style="display:flex">
            <div class="NA-Entry-inlinve-div" style="width:98%;margin-right:5px">
                <label for="id_descriptions">Descriptions</label>
                {{form.descriptions}}
            </div>
        </div>
        <div class="NA-Entry-div-row" style="display:flex">
            <div class="NA-Entry-inlinve-div" style="width:98%">
                <label for="id_reason">Reason</label>
                {{form.reason}}
            </div>
        </div>"
        {{form.fk_goods}}
        {{form.fk_lostby}}
        {{form.fk_fromgoods}}
        {{form.fk_goods_outwards}}
        {{form.fk_goods_lending}}
        {{form.fk_goods_return}}
        {{form.fk_maintenance}}
        {{form.fk_responsibleperson}}
        {{form.fk_usedby}}
        {{form.initializeForm}}
        <input type="submit" style="display:none" id="gLost_submit" />
    </form>
</div>

N_Asset/app/templates/app/MasterData/NA_Entry_Maintenance.html
<div class="row" style="overflow:auto;">

  ﻿<form action="ShowEntry/" method="post" class="form-horizontal" enctype="multipart/form-data" style="background-color:transparent;font-size: 1em;" id="maintenance_form" onsubmit="return false">
     {% csrf_token %}
     <fieldset style="margin-bottom:5px;">
      <legend>Goods Info</legend>
      <div class="NA-Entry-div-row" style="width:550px;">
        <div class="NA-Entry-inlinve-div" style="width:41%">
          <label for="id_serialNum">Serial Number</label>
          {{form.serialNum}}
        </div>
        <div class="NA-Entry-inlinve-div" style="width:58%">
          <label for="id_goods" class="NA-Entry-label;">Search goods</label>
          <div class="input-group" style="display: inline-flex; width: 100%;">
            {{ form.goods }}
            <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
              <button class="btn btn-success" type="button" id="M_FK_goods" style="padding:4px 8px;height: 28px"><span class="glyphicon glyphicon-search"></span></button>
            </span>
          </div>
        </div>
      </div>
      <div class="NA-Entry-div-row" id="difInfo">
        <div class="NA-Entry-inlinve-div">
          <label for="id_itemcode" class="NA-Entry-label;">Item code</label>
          {{ form.itemcode }}
        </div>
        <div class="NA-Entry-inlinve-div">
          <label for="id_typeApp">Type of goods</label>
          {{form.typeApp}}
        </div>
        <div class="NA-Entry-inlinve-div">
          <label for="id_isstillguarantee" class="NA-Entry-Label;">Is Still Guarantee {{ form.isstillguarantee }}
          </label>
        </div>
        <div class="NA-Entry-div-row">
          <div class="NA-Entry-inlinve-div">
            <label for="id_minus">Minus</label>
            {{form.minus}}
          </div>
          <div class="NA-Entry-inlinve-div">
            <label for="id_LastUsed">Last Used By</label>
            <!-- 'class':'NA-Form-Control','placeholder':'Maintenance By','style':'width:225px;' -->
            <input type="text" id="id_LastUsed" name="LastUsed" value="" class="NA_Form-Control" disabled="disabled" style="width:314px">
          </div>
        </div>
      </div>
    </fieldset>
    <div class="NA-Entry-div-row">
      <div class="NA-Entry-inlinve-div">
        <label for="id_requestdate" class="NA-Entry-label;">Request Date</label>
        {{ form.requestdate }}
      </div>
      <div class="NA-Entry-inlinve-div">
        <label for="id_startdate" class="NA-Entry-label;">Start Date</label>
        {{ form.startdate }}
      </div>
      <div class="NA-Entry-inlinve-div">
        <label for="id_expense" class="NA-Entry-label;">Expense</label>
        {{ form.expense }}
      </div>
    </div>
    <div class="NA-Entry-div-row">
      <div class="NA-Entry-inlinve-div" style="width:40%">
        <label for="id_maintenanceby">Maintenance By</label>
        {{ form.maintenanceby }}
      </div>
      <div class="NA-Entry-inlinve-div" style="width:58%">
        <label for="id_personalname">Personal Name</label>
        {{ form.personalname }}
      </div>
    </div>
    <div class="NA-Entry-div-row">
      <div class="NA-Entry-inlinve-div">
        <label for="id_enddate" class="NA-Entry-Label;">End Date</label>
        {{ form.enddate }}
      </div>
      <div class="NA-Entry-inlinve-div">
        <label for="id_issucced" clas="NA-Entry-label" style="margin-left:10px">Is Succed {{ form.issucced }}</label>
      </div>
      <div class="NA-Entry-inlinve-div">
        <label for="id_isfinished" clas="NA-Entry-label" style="margin-left:10px">Is Finished {{ form.isfinished }}</label>
      </div>

    </div>
    <div class="NA-Entry-div-row">
      <div class="NA-Entry-inlinve-div">
        <label for="id_descriptions">Descriptions</label>
        {{form.descriptions}}
      </div>
    </div>
    {{form.fk_goods}}
    {{form.initializeForm}}
    {{form.idapp}}
    <input type="submit" style="display:none" id="maintenance_submit" />
  </form>

</div>

N_Asset/app/templates/app/MasterData/NA_Entry_Permission.html
<style>
form#permission_form .form-control {
	box-shadow:none
}
form#permission_form input.form-control:focus,select.form-control:focus {
    border-color:#4CAF50;
    box-shadow:none
}
fieldset .col-md-3 {
	padding:0;
}
</style>

<div class="row" style="overflow:auto;">
	 <form action="." method="post" class="form-horizontal" style="background-color:transparent;font-size: 1em;" id="permission_form" onsubmit="return false;">
		  {% csrf_token %}
        <fieldset style="margin-bottom:5px;">
            <legend>Form Set</legend>
            <div class="NA-Entry-div-row">
                <label for="serialnumber" class="NA-Entry-label;" style="display:inline-block;margin-right:5px; width:112px;">Form Name</label>
                {{ form.fk_form }}
            </div>
        </fieldset>

		<div class="NA-Entry-div-row" style="border-top:1px solid rgb(11, 153, 16);"></div>

        <fieldset style="margin-bottom:5px;margin-top:5px;" id="fieldset_permission">
            <legend>Permission Set</legend>
            
        </fieldset>
		 {{form.user_id}}
         {{form.allow_view}}
         {{form.allow_add}}
         {{form.allow_edit}}
         {{form.allow_delete}}
		 {{form.initialize_permissionForm}}
		 <input type="submit" style="display:none;" id="permission_submit" />
	 </form>
</div>

N_Asset/app/templates/app/MasterData/NA_Entry_Suplier.html
<style>
    div.NA-Entry-inlinve-div {
        margin-right:5px
    }
</style>
<form action="EntrySuplier/" method="post" style="width:440px;height:260px;" id="suplier_form" onsubmit="return false">
    {% csrf_token %}
    <style>
        form div.row {
            margin-top:15px
        }
    </style>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_supliercode">Supliercode:</label>
            {{form.supliercode}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_supliername">Supliername:</label>
            {{form.supliername}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_telp">Telp:</label>
            {{form.telp}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_hp">Hp:</label>
            {{form.hp}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_contactperson">Contactperson:</label>
            {{form.contactperson}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_inactive" style="display:inline">Inactive:</label>
            {{form.inactive}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_address">Address:</label>
            {{form.address}}
        </div>
    </div>
    
    {{form.initializeForm}}
    <input type="submit" style="display:none" id="suplier_submit" />
    
</form>

N_Asset/app/templates/app/MasterData/NA_F_EmailData.html
<form action="." method="post" onsubmit="return false" id="email_data">
    {% csrf_token %}
    <div class="row" style="margin:0px;display:inline-flex;">
        <div class="col-md-5">
            <label for="id_to" class="left">To:</label> 
            <input class="NA-Form-Control" name="to" required="" id="id_to" type="email" placeholder="example@example.com">
        </div>
        <div class="col-md-7">
            <label for="id_subject" class="left">Subject:</label> 
            <input class="NA-Form-Control" name="subject" required="" id="id_subject" type="text" placeholder="Your Subject .. .">
        </div>
        
    </div>
    <div class="row" style="margin:20px 0 0 0;">
    <div style="padding-left: 15px;" class="col-md-5">
        <label for="selectData" class="left">Select Report: </label>
        <select id="selectData" style="display:block;clear:left;width: 182px;">
            <option value="tabular_data">Tabular Data</option>
            <option value="current_data">Current Data</option>
            <option value="biodata">Bio Data</option>
        </select>
    </div>
    <div style="padding: 0;" class="col-md-7">
    <div style="padding: 0;padding-left: 15px;" class="col-md-5">
            <label for="selectTable" class="left">Select Data: </label>
        </div>
        <div style="padding:0px;clear: left;display: inline-block;position: relative;left: 35px;padding-right: 8px;" class="col-md-11">
            <div class="checkbox checkbox-success" style="padding:0px;text-align: left;margin-top:0px;display: inline-block;float: left;">
                <input id="employee_email" value="employee_emailData" type="checkbox"><label for="employee_email">Employee</label>
            </div>
            <div class="checkbox checkbox-success" style="padding:0px;text-align: left;margin-top:0px;display: inline-block;float: left;margin-left: 30px;">
                <input id="supplier_email" value="supplier_emailData" type="checkbox"><label for="supplier_email">Supplier</label>
            </div>
            <div class="checkbox checkbox-success" style="padding:0px;text-align:left;margin-top:0px;display: inline-block;float: left;margin-left: 30px;">
                <input id="goods_email" value="goods_emailData" type="checkbox"><label for="goods_email">Goods</label>
            </div>
        </div>
    </div>
</div>
    <div class="row" style="margin:12px 0 0 0" id="searchBioContainer">
        <div class="col-md-6" style="padding-right:0">
            <label for="searchBiodata" class="left">Search Data: </label>
            <input class="NA-Form-Control" id="searchBiodata" disabled="disabled" type="text" placeholder="Search biodata .. ." style="width:77%">
        </div>
        <div class="col-md-6" id="resultSearch">

        </div>
    </div>
    <div class="row" style="margin:12px 0 0 0">
        <div class="col-md-12">
            <label for="id_message" class="left">Message:</label>
            <textarea class="NA-Form-Control" name="message" required="" id="id_message" maxlength="250" style="max-width: 500px; width: 462px; height: 52px; clear: left;" placeholder="Enter your message .. ."></textarea>
        </div>
    </div>
    <input type="hidden" id="initializeEmail" />
    <input type="submit" style="display:none" id="emailData_submit"/>
</form>