N_Asset/N_Asset/urls.py
"""
Definition of urls for N_Asset.
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from app.NA_Views.MasterData import NA_Privilege_View
from app.NA_Views import NA_User_View
import app.views
# Uncomment the next lines to enable the admin:
# admin.autodiscover()
from django.contrib import admin
from social_django.urls import *
urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),

    # User's URL
    url(r'^login/$', NA_Privilege_View.na_privilege_login, name='login'),
    url(r'^register/$', NA_Privilege_View.na_privilege_register,
        name='NA_User_Register'),
    url(r'^profile/(?P<username>\w+)/edit/$',
        NA_User_View.user_profile, name='user_profile'),
    url(r'^logout/$', NA_Privilege_View.NA_Privilege_logout, name='logout'),

    # Master Data URL
    url(r'^MasterData/', include('app.NA_Urls.MasterData_url', namespace='MasterData')),

    # Transactions URL
    url(r'^Transactions/',
        include('app.NA_Urls.Transactions_url', namespace='Transactions')),

    # Other Pages URL
    url(r'^OtherPages/', include('app.NA_Urls.OtherPages_url', namespace='OtherPages')),
    
    url(r'^Report/', include('app.NA_Urls.Reports_url', namespace='Report')),

    # Notifications URL
    url(r'^Notifications/', include('NA_Notifications.urls',
                                    namespace='NA_Notifications')),

    # URL Facebook,Google,Twitter Login
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
]

# untuk akses url media(picture) hasil upload User
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    #import debug_toolbar
    #urlpatterns += [
    #   url(r'^__debug__/', include(debug_toolbar.urls)),]

N_Asset/NA_Models/models.py
import re
from datetime import date, datetime, timedelta
from os import path

from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import FieldError, MultipleObjectsReturned
from django.db import models
from django.utils import timezone
from django.utils.encoding import force_text
from NA_DataLayer.fields import JSONField
from NA_DataLayer.MasterData.NA_Employee import NA_BR_Employee
from NA_DataLayer.MasterData.NA_Goods_BR import NA_BR_Goods, CustomManager
from NA_DataLayer.MasterData.NA_Privilege_BR import NA_BR_Privilege
from NA_DataLayer.MasterData.NA_Supplier import NA_BR_Supplier
from NA_DataLayer.MasterData.NA_Sys_Privilege_BR import NA_BR_Sys_Privilege
from NA_DataLayer.OtherPages.NA_Acc_FA import NA_Acc_FA_BR
from NA_DataLayer.OtherPages.NA_Maintenance_BR import NA_BR_Maintenance
from NA_DataLayer.Transactions.NA_Ga_History_BR import NAGaVnHistoryBR
from NA_DataLayer.Transactions.NA_GoodsLost_BR import NA_BR_GoodsLost
from NA_DataLayer.Transactions.NA_Goods_Disposal_BR import NA_BR_Goods_Disposal
from NA_DataLayer.Transactions.NA_Goods_Lending_BR import NA_BR_Goods_Lending
from NA_DataLayer.Transactions.NA_Goods_Maintenance_GA_BR import NA_BR_GA_Maintenance
from NA_DataLayer.Transactions.NA_Goods_Outwards_BR import NA_BR_Goods_Outwards
from NA_DataLayer.Transactions.NA_Goods_Outwards_GA_BR import NABRGoodsOutwardsGA
from NA_DataLayer.Transactions.NA_Goods_Receive_BR import (NA_BR_Goods_Receive,
                                                           CustomSupplierManager,
                                                           custEmpManager)
from NA_DataLayer.Transactions.NA_Goods_Receive_Detail_BR import NA_BR_Goods_Receive_Detail
from NA_DataLayer.Transactions.NA_Goods_Receive_GA_BR import NA_BR_Goods_Receive_GA
from NA_DataLayer.Transactions.NA_Goods_Receive_Other_BR import NA_BR_Goods_Receive_other
from NA_DataLayer.Transactions.NA_Goods_Return_BR import NA_BR_Goods_Return
from NA_DataLayer.Transactions.NA_Goods_Return_GA_BR import NA_BR_Goods_Return_GA
#from NA_DataLayer.Transactions.
from NA_DataLayer.file_storage import NAFileStorage


class NA_BaseModel(models.Model):
    idapp = models.AutoField(db_column='IDApp', primary_key=True)
    createddate = models.DateTimeField(
        db_column='CreatedDate', default=timezone.now)
    createdby = models.CharField(db_column='CreatedBy', max_length=100)
    modifieddate = models.DateTimeField(
        db_column='ModifiedDate',
        blank=True,
        null=True
    )
    modifiedby = models.CharField(
        db_column='ModifiedBy',
        max_length=100,
        blank=True,
        null=True
    )

    class Meta:
        abstract = True


class NA_MasterDataModel(NA_BaseModel):
    typeapp = models.CharField(db_column='TypeApp', max_length=32)
    inactive = models.BooleanField(db_column='InActive', default=False)
    descriptions = models.CharField(
        db_column='Descriptions',
        max_length=250,
        blank=True,
        null=True
    )

    class Meta:
        abstract = True


class NA_TransactionModel(NA_BaseModel):
    fk_goods = models.ForeignKey(
        'goods',
        db_column='FK_Goods',
        max_length=30,
        db_constraint=False,
    )
    fk_employee = models.ForeignKey(
        'Employee',
        db_column='FK_Employee',
        db_constraint=False
    )
    typeapp = models.CharField(db_column='TypeApp', max_length=32)
    serialnumber = models.CharField(
        db_column='SerialNumber',
        max_length=100,
        default='N/A'
    )

    class Meta:
        abstract = True


class NA_GoodsReceiveModel(NA_BaseModel):
    datereceived = models.DateTimeField(db_column='DateReceived')
    fk_supplier = models.ForeignKey(
        'NASupplier',
        db_column='FK_Supplier',
        db_constraint=False
    )
    totalpurchase = models.SmallIntegerField(db_column='TotalPurchase')
    totalreceived = models.SmallIntegerField(db_column='TotalReceived')
    descriptions = models.CharField(
        db_column='Descriptions',
        max_length=250,
        blank=True,
        null=True
    )
    descbysystem = models.CharField(
        db_column='DescBySystem',
        max_length=2000,
        blank=True,
        null=True
    )
    refno = models.CharField(db_column='REFNO', max_length=100)

    class Meta:
        abstract = True


class NAGoodsOutwardsModel(NA_TransactionModel):
    isnew = models.BooleanField(db_column='IsNew')
    daterequest = models.DateTimeField(db_column='DateRequest')
    datereleased = models.DateTimeField(db_column='DateReleased')
    fk_usedemployee = models.ForeignKey(
        'Employee',
        db_column='FK_UsedEmployee',
        related_name='rel_used_employee_%(class)s',
        null=True,
        db_constraint=False
    )
    fk_frommaintenance = models.ForeignKey(
        'Employee',
        related_name='rel_maintenance_%(class)s',
        db_column='FK_FromMaintenance',
        blank=True,
        null=True,
        db_constraint=False
    )
    fk_responsibleperson = models.ForeignKey(
        'Employee',
        db_column='FK_ResponsiblePerson',
        max_length=50,
        blank=True,
        null=True,
        related_name='rel_resp_person_%(class)s',
        db_constraint=False
    )
    fk_sender = models.ForeignKey(
        'Employee',
        related_name='rel_sender_%(class)s',
        db_column='FK_Sender',
        max_length=50,
        blank=True,
        null=True,
        db_constraint=False
    )
    fk_stock = models.ForeignKey(
        'NAStock',
        related_name='rel_stock_%(class)s',
        db_column='FK_Stock',
        blank=True,
        null=True,
        db_constraint=False
    )
    fk_lending = models.ForeignKey(
        'NAGoodsLending',
        db_column='FK_Lending',
        related_name='rel_lending_%(class)s',
        null=True,
        blank=True,
        db_constraint=False
    )
    fk_return = models.ForeignKey(
        'NAGoodsReturn',
        db_column='FK_Return',
        related_name='rel_return_%(class)s',
        null=True,
        db_constraint=False
    )
    fk_receive = models.ForeignKey(
        'NA_GoodsReceive_detail',
        db_column='FK_Receive',
        related_name='rel_receive_%(class)s',
        null=True,
        db_constraint=False
    )
    lastinfo = models.CharField(
        db_column='lastinfo', max_length=250, blank=True, null=True)
    descriptions = models.CharField(
        db_column='Descriptions',
        max_length=250,
        blank=True,
        null=True
    )

    class Meta:
        abstract = True


class NAGoodsReturnModel(NA_TransactionModel):
    datereturn = models.DateTimeField(db_column='DateReturn')
    conditions = models.CharField(db_column='Conditions', max_length=1)
    fk_fromemployee = models.ForeignKey(
        'Employee',
        db_column='FK_FromEmployee',
        max_length=50,
        blank=True,
        null=True,
        related_name='fk_ngr_fromemployee_%(class)s',
        db_constraint=False
    )
    fk_usedemployee = models.ForeignKey(
        'Employee',
        db_column='FK_UsedEmployee',
        max_length=50,
        blank=True,
        null=True,
        related_name='fk_ngr_usedemployee_%(class)s',
        db_constraint=False
    )
    isaccepted = models.PositiveSmallIntegerField(db_column='IsAccepted',default=0)
    iscompleted = models.PositiveSmallIntegerField(db_column='IsCompleted')
    minusDesc = models.CharField(
        db_column='MinusDesc',
        max_length=100,
        blank=True,
        null=True
    )
    fk_goods_outwards = models.ForeignKey(
        'NAGoodsOutwards',
        db_column='FK_Goods_Outwards',
        null=True,
        blank=True,
        related_name='fk_outwards_%(class)s',
        db_constraint=False
    )
    fk_goods_lend = models.ForeignKey(
        'NAGoodsLending',
        db_column='FK_Goods_Lend',
        blank=True,
        null=True,
        related_name='fk_lend_%(class)s',
        db_constraint=False
    )
    descriptions = models.CharField(
        db_column='Descriptions',
        max_length=250,
        blank=True,
        null=True
    )

    class Meta:
        abstract = True


class LogEvent(NA_BaseModel):
    modifieddate = None
    modifiedby = None

    nameapp = models.CharField(db_column='NameApp', max_length=30)
    model = models.CharField(db_column='Model', max_length=30)
    descriptions = JSONField()

    def __str__(self):
        return '{}'.format(self.nameapp)

    @staticmethod
    def get_log_data(model, action, values=None, pk=None, **kwargs):
        """
        to get log event data, use it to get date informations if data has deleted,
        existed or updated
        param
        action: e.g (deleted,updated)
        action for getting type of log event

        PK: primary key e.g (IDApp,SupplierCode)
        model: can fill with model class or string
        usage :: LogEvent.get_log_data(pk=1, model=Employee, action='Deleted',
        values='createddate')
        """

        filter_kwargs = {
            'nameapp__istartswith': action,
            'model': model
        }

        if not isinstance(model, type):
            try:
                model = ContentType.objects.get(model=model)
            except ContentType.DoesNotExist:
                raise ValueError('cannot get model %s' % model)
            model = model.model_class()

        if pk is None:
            for field in kwargs.keys():
                filter_kwargs.update({
                    'descriptions__%s' % field: kwargs.get(field)
                })
        else:
            pk_field = model._meta.pk.name
            filter_kwargs.update({
                'descriptions__%s' % pk_field: pk
            })
        filter_kwargs['model'] = force_text(
            model._meta.verbose_name).replace(' ', '')

        try:
            log = LogEvent.objects.get(**filter_kwargs)
        except FieldError:

N_Asset/app/templates/app/Transactions/NA_Entry_Equipment.html
<form id="entry_equipment_form" onsubmit="return false;">
    {% csrf_token %}
    <div class="NA-Entry-inlinve-div">
        <label style="display:inline-block; width:60px;">Name</label>
        {{ form.name_app }}
    </div>
    <input id="submit_entry_equipment" type="submit" style="display:none;" />
</form>

N_Asset/app/templates/app/Transactions/NA_Entry_Goods_Receive_GA.html
<div class="row" style="overflow:auto;">
    <form action="." method="post" class="form-horizontal"
          style="background-color:transparent;font-size: 1em;width:520px;max-height:500px;overflow:auto;" 
		  id="form_ga_receive" onsubmit="return false;">
        {% csrf_token %}
        <fieldset style="margin-bottom:5px;">
            <legend>Goods Info</legend>
            <div class="NA-Entry-div-row">
                <label for="id_itemcode" class="NA-Entry-label;" style="display:inline-block; width:100px;">Goods</label>
                {{ form.itemcode }}
                <div class="input-group" style="display: inline-flex; width: 50%;position:relative;top:2px;">
                    {{ form.goodsname }}
                    <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                        <button class="btn btn-success" type="button" id="btn_fk_goods" style="padding:4px 8px;height: 28px"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                </div>
            </div>
            <div class="NA-Entry-div-row" id="difInfo" style="display:none">
                <!--Khusus untuk Goods Info setelah di pilih-->
                <div style="margin-bottom:5px;margin-right:auto;display:flex;">
                    <label id="BrandKey" class="NA-Entry-label;" style="display:inline-block;width:100px;">Brand</label>
                    <label id="BrandValue" class="NA-Entry-label;" style="margin-right: 5px;width: 75%;display: inline-block;border: 1px solid rgb(76, 175, 80);border-top-right-radius: 5px;padding-left: 5px;">{{ form.brandvalue.value }}</label>
                </div>
                <div style="margin-bottom:5px;margin-right:auto;display:flex;">
                    <label id="TypeKey" class="NA-Entry-label;" style="display:inline-block;width:100px;">Tipe</label>
                    <label id="TypeValue" class="NA-Entry-label;" style="margin-right: 5px;width: 75%;display: inline-block;border: 1px solid rgb(76, 175, 80);border-top-right-radius: 5px;padding-left: 5px;">{{ form.typeapp.value }}</label>
                </div>
                <div style="margin-bottom:5px;margin-right:auto;display:flex;">
                    <label id="fk_goodsKey" class="NA-Entry-label;" style="display:inline-block;margin-right:5px; width:100px;">Item Code</label>
                    <label id="fk_goodsValue" class="NA-Entry-label;" style="margin-right: 5px;width: 75%;display: inline-block;border: 1px solid rgb(76, 175, 80);border-top-right-radius: 5px;padding-left: 5px;">{{ form.fk_goods.value }}</label>
                </div>
            </div>
        </fieldset>

        <div class="NA-Entry-div-row" style="border-top:1px solid rgb(11, 153, 16);">
            <fieldset style="margin-bottom:5px;margin-top:5px;">
                <legend>Receiving Info</legend>
                <div style="margin-bottom:5px;margin-right:auto">
                    <label for="id_suppliercode" class="NA-Entry-label;" style="display:inline-block;width:100px;">Supplier</label>
                    {{ form.suppliercode }}
                    <div class="input-group" style="display:inline-flex;width:50%;">
                        {{ form.suppliername }}
                        <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                            <button class="btn btn-success" type="button" id="btn_fk_supplier" style="padding:4px 8px;height: 28px;"><i class="glyphicon glyphicon-search"></i></button>
                        </span>
                    </div>
                </div>
                <div style="margin-bottom:5px;margin-right:auto">
                    <label for="id_pr_by_nik" class="NA-Entry-label;" style="display:inline-block;width:100px;">PR By</label>
                    {{ form.pr_by_nik }}
                    <div class="input-group" style="display:inline-flex;width:50%;">
                        {{ form.pr_by_name }}
                        <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                            <button class="btn btn-success" type="button" id="btn_fk_pr_by" style="padding:4px 8px;height: 28px;"><i class="glyphicon glyphicon-search"></i></button>
                        </span>
                    </div>
                </div>
                <div style="margin-bottom:5px;margin-right:auto">
                    <label for="fk_received_by_nik" class="NA-Entry-label;" style="display:inline-block;width:100px;">Received By</label>
                    {{ form.received_by_nik }}
                    <div class="input-group" style="display:inline-flex;width:50%;">
                        {{ form.received_by_name }}
                        <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                            <button class="btn btn-success" type="button" id="btn_fk_received_by" style="padding:4px 8px;height: 28px;"><i class="glyphicon glyphicon-search"></i></button>
                        </span>
                    </div>
                </div>
                <div style="margin-bottom:5px;margin-right:auto">
                    <label for="id_datereceived" class="NA-Entry-label;" style="display:inline-block; width:100px;">Date received</label>
                    {{ form.datereceived }}
                </div>
            </fieldset>
        </div>
        <div class="NA-Entry-div-row" style="border-top:1px solid rgb(11, 153, 16);">
            <fieldset style="margin-bottom:5px;margin-top:5px;">
                <legend>More Detail</legend>
                <div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_brand" style="display:inline-block; width:100px;">Brand</label>
                        {{ form.brand }}
                    </div>
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_typeapp" style="display:inline-block; width:85px;margin-left:10px;">Type</label>
                        {{ form.typeapp }}
                    </div>
                </div>
				<div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_model" style="display:inline-block; width:100px;">Model</label>
                        {{ form.model }}
                    </div>
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_kind" style="display:inline-block; width:85px;margin-left:10px;">Kind</label>
                        {{ form.kind }}
                    </div>
                </div>
				<div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_year_made" style="display:inline-block; width:100px;">Year made</label>
                        {{ form.year_made }}
                    </div>
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_colour" style="display:inline-block; width:85px;margin-left:10px;">Colour</label>
                        {{ form.colour }}
                    </div>
                </div>
				<div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_fuel" style="display:inline-block; width:100px;">Fuel</label>
                        {{ form.fuel }}
                    </div>
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_cylinder" style="display:inline-block; width:85px;margin-left:10px;">Cylinder</label>
                        {{ form.cylinder }}
                    </div>
                </div>
				<div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_invoice_no" style="display:inline-block; width:100px;">Invoice no</label>
                        {{ form.invoice_no }}
                    </div>
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_machine_no" style="display:inline-block; width:85px;margin-left:10px;">Machine no</label>
                        {{ form.machine_no }}
                    </div>
                </div>
                <div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_price" style="display:inline-block; width:100px;">Price</label>
                        {{ form.price }}
                    </div>
                </div>
				<div style="margin-bottom:5px;margin-right:auto">
                    <div class="NA-Entry-inlinve-div">
                        <label for="id_chassis" style="display:inline-block; width:100px;">Chassis no</label>
                        {{ form.chassis_no }}
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="NA-Entry-div-row" style="border-top:1px solid rgb(11, 153, 16);">
            <fieldset style="margin-bottom:5px;margin-top:5px;">
                <legend>Directly Enter Vehicle Number Ownership ?</legend>
                <div class="NA-Entry-inlinve-div" style="padding-left:10px;padding-bottom:10px;">
                    {{ form.direct_enter }} Yes
                </div>
                <div style="margin-bottom:5px;margin-right:auto;display:none;" id="enter_direct_container">

                    <div class="NA-Entry-div-row">
                        <label for="id_reg_no" style="display:inline-block; width:100px;">Reg no</label>
                        {{ form.reg_no }}
                    </div>
                    <div class="NA-Entry-div-row">
                        <label for="id_date_reg" style="display:inline-block; width:100px;">Date reg</label>
                        {{ form.date_reg }}
                    </div>

                    <div class="NA-Entry-div-row" style="margin-top:20px;display:none;" id="reg_info">
                        <div style="margin-bottom:5px;margin-right:auto;display:flex;">
                            <label id="expired_reg_label" class="NA-Entry-label;" style="display:inline-block;width:100px;">Expired Reg</label>
                            <label id="expired_reg_value" class="NA-Entry-label;" 
                            style="margin-right: 5px;width: 75%;display: 
                            inline-block;border: 1px solid rgb(76, 175, 80);
                            border-top-right-radius: 5px;padding-left: 5px;">{{ form.expired_reg.value }}</label>
                        </div>

                        <div style="margin-bottom:5px;margin-right:auto;display:flex;">
                                <label id="bpkb_label" class="NA-Entry-label;" style="display:inline-block;width:100px;">BPKB Expired</label>
                                <label id="bpkb_value" class="NA-Entry-label;" 
                                style="margin-right: 5px;width: 75%;display: 
                                inline-block;border: 1px solid rgb(76, 175, 80);
                                border-top-right-radius: 5px;padding-left: 5px;">{{ form.bpkb_expired.value }}</label>
                        </div>
                    </div>
                    <div class="NA-Entry-div-row">
                        <label for="id_remark">Remark</label>
                        {{ form.remark }}
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="NA-Entry-div-row">
            <label for="id_descriptions" class="NA-Entry-label;">Descriptions / Remark</label>
            {{ form.descriptions }}
        </div>
        <input type="submit" style="display:none" id="submit_receive_ga">
        {{ form.initializeForm }}
        {{ form.fk_goods }}
        {{ form.pr_by }}
        {{ form.received_by }}
        {{ form.expired_reg }}
        {{ form.bpkb_expired }}
    </form>
</div>

N_Asset/app/templates/app/Transactions/NA_Entry_Goods_Receive_other.html
<div class="row" style="overflow:auto;">
    <form action="." method="post" class="form-horizontal" style="background-color:transparent;font-size: 1em;" id="gReceive_other_form" onsubmit="return false;">
        {% csrf_token %}
        <div class="NA-Entry-div-row">
            <div class="NA-Entry-inlinve-div">
                <label for="refno" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:112px;">RefNO</label>
                {{ form.refno }}
            </div>
            <div class="NA-Entry-inlinve-div">
                <label for="datereceived" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:100px;">date received</label>
                {{ form.datereceived }}
            </div>
        </div>
        <div class="NA-Entry-div-row">
            <label for="fk_goods" class="NA-Entry-label;" style="display:inline-block;margin-right:5px; width:112px;">Goods Desc</label>
            {{ form.fk_goods }}
            <div class="input-group" style="display: inline-flex; width: 46%;">
                {{ form.goods_desc }}
                <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                    <button class="btn btn-success" type="button" id="btn_fk_goods" style="padding:4px 8px;height: 28px">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </div>
        <div class="NA-Entry-div-row">
            <label for="supplier" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:112px;">Supplier</label>
            {{ form.fk_supplier }}
            <div class="input-group" style="display:inline-flex; width:46%;">
                {{ form.suppliername }}
                <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                    <button class="btn btn-success" type="button" id="btn_fk_supplier" style="padding:4px 8px;height: 28px;">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
            </div>
        </div>

        <div class="NA-Entry-div-row">
            <div class="NA-Entry-inlinve-div">
                <label for="totalpurchase" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:112px;">Total Purchased</label>
                {{ form.totalpurchase}}
            </div>
            <div class="NA-Entry-inlinve-div">
                <label for="totalreceived" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:112px;">Total Received</label>
                {{ form.totalreceived}}
            </div>
        </div>
        <div class="NA-Entry-div-row">
            <label for="fk_pr_by" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:112px;;">PR By</label>
            {{ form.fk_p_r_by }}
            <div class="input-group" style="display:inline-flex;width:46%;">
                {{ form.employee_pr }}
                <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                    <button class="btn btn-success" type="button" id="btn_fk_p_r_by" style="padding:4px 8px;height: 28px;">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
            </div>
        </div>
        <div class="NA-Entry-div-row">
            <label for="fk_receivedby" class="NA-Entry-label;" style="display:inline-block;margin-right:5px;width:112px;">Received By</label>
            {{ form.fk_receivedby }}
            <div class="input-group" style="display:inline-flex;width:46%;">
                {{ form.employee_received }}
                <span class="input-group-btn" style="display:inline-flex;height: 28px;padding-bottom:0;justify-content:flex-end">
                    <button class="btn btn-success" type="button" id="btn_fk_receivedby" style="padding:4px 8px;height: 28px;">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
            </div>
        </div>
        <div class="NA-Entry-div-row">
            <div class="NA-Entry-inlinve-div">
                <label for="descriptions" class="NA-Entry-label;">Descriptions / Remark / Unit</label>
                {{ form.descriptions }}
            </div>
        </div>
        <input type="submit" style="display:none" id="goods_receive_other_submit">
        {{ form.initializeForm }}
        {{ form.idapp }}
        {{ form.idapp_fk_goods }}
        {{ form.idapp_fk_p_r_by }}
        {{ form.idapp_fk_receivedby }}
        {{ form.hasRefData }}
        {{ form.descbysystem }}
        {{ form.typeApp}}
    </form>
</div>

N_Asset/app/templates/app/Transactions/NA_R_Goods_Outwards.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="Cache-control" content="no-cache">
</head>
<body>
    <embed height="100%" width="100%" name="plugin" src={{ result }} type="application/pdf">
</body>